spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          username: ${CONFIG_GIT_USERNAME}
          password: ${CONFIG_GIT_PASSWORD}
server:
  port: 8888

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD}