sudo: required

language: java
jdk: oraclejdk8
services:
  - docker
before_install:
  # set up awscli packages
  - pip install --user awscli
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

env:
  global:
    - secure: aIAyRaSfgbkyccfjD/Q5ivCXdrXwv4mdKuDQY8I9x/dBC72/aUI2jqDAPtKX+1EiiAa705XVDKYQHsicVfm+J0f67ZXYBGC6EhQHkikx0o4F6v7hwWTTmHnY/fc9S7r1xEMwaGtDnn2//kNrX/2grUedoY0G1CX9qPWZdEN/MrmD5PtorTAPt6yxaVhsi1Edx09ZqDDl8Zk2o+tWdauioP6NPXLTy5bt4flE5B7VxixmOE6Y36+NBv5s3h1pvttaKhWZlHZv/egn6xaVJohomGvpUKVikoRsST7kF9zf3dUDxzKKwtbZB7GuTV8mxeuRZfFvmJ/Y+GYlziTOiYQnySBOnEr+S9wLNdRpN4aB2HsTkM3qr7RHETLP7oWxmvv0BtY0+4Sw1dffnzjAOyAgjhqf2GucFnjGddJbCYgJm5nElahjGig4jxT0DGN1fyCm9WnxS5Fm4DObUL8TF8oNfoVrkGUKG4TqWjZJKWEACiqu8NWEEayUojucP+k6QBhHciCG/E++l9n+NyBSNYCeF0kgPcR/hv6LVEC3geZkG8l7yUX5Jz/fRi/0e5rHktttFl6YqPmuQC20X6XlAbFecWXnQCU6rvvLsShgurqBdo5oaeZTOpeyULpa657NMY8oTdP+VVtAysf75ZcJSXM5PpEZJJocUZToAzuY4aA4BuM=
    - secure: QKEmmcUWnpTSO0OYepspOTCmpP8zDPQiUpAY0qCAE0PL8VzwRcmMfWo48/c8zbjTS8rGZ/BoU6Bk79hlC9XwIMbhrFinaEbmqv78M5usI5TJsXOE6rAfOK41YpQRrL/FPmfi0caRs262yrstTYnX6MJsuykWnKLyVLDrS0aQmPFeA/OXgmhiHeABMtanJMG1HsBj2TveyRhEKY5n1plVgtp8YQuymjIlihDgM0Ag7pWDQ8cymF/FSqpBFaYaCn6ApfFuuC1nFErEghDTA3bjnC6u0BegEodzCutk8yWkaj497TRLgJ51vjb77SNuzBK6cWniV4S4xveP3gBtJhoL6cr6WmyRaHewbyOdYXWtRw8BLVK9tChzN4Qgz5QNBYvDr/2ZwmKdk+zDKlqU5pnwfVCAyAzrOP2cqgBSVcELCb0DNGtQDDxaiIYJjGTsKf6GnmkJSChUO+r80DrVUfoidH3K51X6vWGiAzjotxNrnUTniTb0zg2UZPj49eBV7Xz5d/vOp4DYZBsTKEdqsS1sgIDm0WYdEt435HY/07Y8I7iwZIprPciKJiCPomKv9r/+9wLLXRtfMAMwWpnypTO5Qo3kU6FPmoDY25Z6zs891LREtAt4Zn2qstRuOTkgXQXj0mh7z7RvltGeq8tX2ig3bV8pKE2AjViWpfGU5T+rAq4=
    - secure: oXzHh56Zf/oWgkyuFjvJCTugU/+j86ldVW3f0Xt0RgP2oTyguUrlWEwtistTxa0xS9Pf0JgDqjBWCzIS5abmjCvUjrQh5QJsz/aYOz6JeELDTeA0YCfO4II1uwqtCcYVk/UNMciEzYlWvj2TqbGGiuynkX3ZUs5rYemUOulHy/018Swb89eOvGA1AiT5KHh5Zgte1nmPEjP7bNAe8F3aC8D0nqgbjxbk+BpTcjdxvYDyOYsKNlXDbYGgeb1KdFadmSSuwtKuS8MkxxwCv+fcWtlDOA5OAFIDMPiTwaRllQRDvK3HLrXpcEMT+zWZSMFZ0jj+p6I0Tc8yG2d8/eNcSkTiL+wJ1ccYy6niyV2TYaHAVq9OorNg/8vPqHYzwugH19tkSgxg2SHVEafkQyxC/d5x4524VtZxm3z8E28CYp9b1WDn4u4NbxYAva0CELpkCCpAl5coi46+NDmk14wJUDVoy6wkv/pbY2vqQohRM7gpviQdx6m3MED+i2pjE2pKhhoePQ5oXkX9DO6Cl/Xo7n3B2li8yXR0eyFN9Wlae691ZeUGSGYRzK96nO7XMAZcjBP3PhrMVhGIk7QoTaLYkmZFK8+GZNnCQs+xVvGf0xf4Pij2E5fgoS8bxijkBuhyoaZw5+8XigEkW5eiqKJ1TFMuzu6gyAASgO5JoEHj0Nw=
    - COMMIT=${TRAVIS_COMMIT::7}
    - REPO=115056349306.dkr.ecr.us-east-1.amazonaws.com

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - export TAG=`if [ "$TRAVIS_BRANCH" == "travis_test" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    - export DOCKER_LOGIN = `aws ecr get-login --region us-east-2`
    - $DOCKER_LOGIN
    - export CLASSIFICATORS_SERVICE=classificators
    - docker build -t $CLASSIFICATORS_SERVICE:$COMMIT ./classififcators
    - docker tag $CLASSIFICATORS_SERVICE:$COMMIT $REPO/$CLASSIFICATORS_SERVICE:$TAG
    - docker push $REPO/$CLASSIFICATORS_SERVICE:$TAG
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: classificators/build/asciidoc/html5
  on:
    branch: master
