version: '2'
services:
  classificators:
    environment:
      CONFIG_SERVICE_PASSWORD: 123
      NOTIFICATION_SERVICE_PASSWORD: 123
      MONGODB_PASSWORD: 123
    image: 115056349306.dkr.ecr.us-east-1.amazonaws.com/classificators
    links:
      - mongodb
    ports:
      - "80:8080"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    mem_limit: 300000000
  mongodb:
    image: sameersbn/mongodb:latest
    environment:
        INIT_DUMP: classificators-dump.js
        MONGODB_PASSWORD: 123
    ports:
      - "27017:27017"
    volumes:
      - /tmp/docker/mongodb:/var/lib/mongodb
    mem_limit: 300000000