version: '3'
services:
  classificators:
    build: classificators
  config:
    build: config
  registry:
    build: registry
  monitoring:
    build: monitoring
  gateway:
    build: gateway
  classificators-mongodb:
    build: classificators-mongodb