version: '2'
services:
  config:
    environment:
      CONFIG_SERVICE_PASSWORD: 123
      MONGODB_PASSWORD: 123
    image: 115056349306.dkr.ecr.us-east-1.amazonaws.com/config
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    mem_limit: 300000000