version: '3'
services:
  classificators:
    build: classificators
    environment:
      - SPRING_PROFILES_ACTIVE=local,debug,native
      - CONFIG_SERVICE_PASSWORD=123
      - NOTIFICATION_SERVICE_PASSWORD=123
      - MONGODB_PASSWORD=123
  config:
    build: config
    environment:
      - SPRING_PROFILES_ACTIVE=local,debug,native
  registry:
    build: registry
  monitoring:
    build: monitoring
  gateway:
    build: gateway
  classificators-mongodb:
    build: classificators-mongodb