version: '2'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  mongodb:
    build: mongodb
    ports:
      - 26000:27017

  webclient:
    build: webclient

  classificators:
    build: classificators
    ports:
      - 6000:6000

  monitoring:
      build: monitoring