version: '2'
services:
  rabbitmq:
      image: rabbitmq:3-management
      restart: always
      ports:
        - 15672:15672
      logging:
        options:
          max-size: "10m"
          max-file: "10"

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: registry
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  webclient:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: webclient
    restart: always
    ports:
      - 8181:1000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  classificators:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
    build: classificators
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

