version: '3'
services:
  classificators-mongodb:
    image: 115056349306.dkr.ecr.us-east-1.amazonaws.com/classificators-mongodb:0.0.1
    ports:
      - 27017:27017
    environment:
      - MONGODB_PASSWORD=123
    volumes:
      - db-data:/var/lib/mongodb
  classificators:
    image: 115056349306.dkr.ecr.us-east-1.amazonaws.com/classificators:local
    ports:
      - 8080:8080
    environment:
      - CONFIG_SERVICE_PASSWORD=123
      - NOTIFICATION_SERVICE_PASSWORD=123
      - MONGODB_PASSWORD=123
    depends_on:
      - classificators-mongodb
      - config
      - registry
    deploy:
      restart_policy:
        condition: none
  config:
    image: 115056349306.dkr.ecr.us-east-1.amazonaws.com/config:0.0.2
    ports:
      - 8888:8888
    environment:
      CONFIG_SERVICE_PASSWORD: 123
      MONGODB_PASSWORD: 123
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  registry:
    image: 115056349306.dkr.ecr.us-east-1.amazonaws.com/registry:0.0.2
    ports:
      - 8761:8761
    environment:
      CONFIG_SERVICE_PASSWORD: 123
    depends_on:
      - config
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  gateway:
    image: 115056349306.dkr.ecr.us-east-1.amazonaws.com/gateway:0.0.2
    ports:
      - 80:4000
    environment:
      CONFIG_SERVICE_PASSWORD: 123
    depends_on:
      - config
      - registry
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
volumes:
  db-data: