spring:
  data:
    mongodb:
      host: classificators-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: okpd
      port: 27017

server:
  context-path: /classificators
  port: 6000
