spring:
  data:
    mongodb:
      host: localhost
      database: okpd
      port: 27017
      username: user
      password: 123
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user
  profiles:
    active: debug
server:
  context-path: /classificators
  port: 8080
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
          defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

